# Generated by Django 5.2.5 on 2025-08-27 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetanimal', '0002_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='vetanimal.animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='vetanimal.doctor'),
            preserve_default=False,
        ),
    ]
