# Generated by Django 5.2.5 on 2025-08-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetanimal', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vetanimal.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
