# Generated by Django 5.2.5 on 2025-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetanimal', '0006_appointment_category_delete_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
