# Generated by Django 5.2.5 on 2025-08-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetanimal', '0003_record_delete_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='animal',
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='vetanimal.category'),
            preserve_default=False,
        ),
    ]
